package io.opennoodoe.app.companion;
import android.app.*;
import android.widget.*;
import android.text.InputFilter;
/** Local configuration only; opening or saving this editor sends no message. */
public final class ReplySettingsDialog {
 public static void show(Activity a){ReplySettings current=new ReplySettings(a);LinearLayout rows=new LinearLayout(a);rows.setOrientation(LinearLayout.VERTICAL);int pad=(int)(16*a.getResources().getDisplayMetrics().density);rows.setPadding(pad,pad,pad,pad);
  TextView hint=new TextView(a);hint.setText(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0679,"빈 항목은 제외돼요. 누도에서 알림을 열고 O 길게 → 문구 선택 → O로 전송해요. 서명은 모든 답장 끝에 붙어요."));rows.addView(hint);
  EditText[] text=new EditText[5];for(int i=0;i<5;i++){text[i]=new EditText(a);text[i].setHint(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0680,"빠른 답장 ")+(i+1));text[i].setFilters(new InputFilter[]{new InputFilter.LengthFilter(120)});if(i<current.replies.size())text[i].setText(current.replies.get(i));rows.addView(text[i]);}
  EditText signature=new EditText(a);signature.setHint(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0681,"서명 (비우면 사용 안 함)"));signature.setFilters(new InputFilter[]{new InputFilter.LengthFilter(160)});signature.setText(current.signature);rows.addView(signature);
  EditText name=new EditText(a);name.setHint(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0682,"계기판에 표시할 폰 이름"));name.setFilters(new InputFilter[]{new InputFilter.LengthFilter(40)});name.setText(a.getSharedPreferences("companion",0).getString("device.name",android.os.Build.MODEL));rows.addView(name);
  Spinner region=new Spinner(a);region.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0683,"자동 (일본어 / 대만 번체)"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0684,"일본어 글자 형태"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0685,"대만 번체 글자 형태")}));String old=a.getSharedPreferences("companion",0).getString("cjk.region","auto");region.setSelection(old.equals("jp")?1:old.equals("tc")?2:0);rows.addView(region);
  TextView note=new TextView(a);note.setText(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0686,"문자 지역·폰 이름 변경은 연동을 다시 시작하면 적용돼요. 최근 알림은 RAM에만 10개 보관해요. 답장 가능한 앱만 지원해요."));rows.addView(note);
  Button license=new Button(a);license.setText(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0687,"Noto 글꼴 라이선스"));license.setOnClickListener(v->{try(java.io.InputStream in=a.getAssets().open("fonts/LICENSE.txt")){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] b=new byte[2048];for(int n;(n=in.read(b))!=-1;)out.write(b,0,n);new AlertDialog.Builder(a).setTitle("Noto CJK · SIL OFL 1.1").setMessage(out.toString("UTF-8")).setPositiveButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0009,"닫기"),null).show();}catch(Exception e){Toast.makeText(a,io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0688,"라이선스를 열지 못했어요."),Toast.LENGTH_LONG).show();}});rows.addView(license);
  Button icons=new Button(a);icons.setText(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0689,"Google Material 아이콘 라이선스"));icons.setOnClickListener(v->{try(java.io.InputStream in=a.getResources().openRawResource(io.opennoodoe.app.R.raw.material_icons_license)){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] b=new byte[2048];for(int n;(n=in.read(b))!=-1;)out.write(b,0,n);new AlertDialog.Builder(a).setTitle("Google Material Icons · Apache 2.0").setMessage(out.toString("UTF-8")).setPositiveButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0009,"닫기"),null).show();}catch(Exception e){Toast.makeText(a,io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0688,"라이선스를 열지 못했어요."),Toast.LENGTH_LONG).show();}});rows.addView(icons);
  ScrollView scroll=new ScrollView(a);scroll.addView(rows);AlertDialog dialog=new AlertDialog.Builder(a).setTitle(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0690,"빠른 답장과 문자 표시")).setView(scroll).setNegativeButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0004,"취소"),null).setPositiveButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0170,"저장"),null).create();
  dialog.setOnShowListener(v->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(button->{try{String[] r=new String[5];for(int i=0;i<5;i++)r[i]=text[i].getText().toString();ReplySettings.save(a,r,signature.getText().toString());String selected=new String[]{"auto","jp","tc"}[region.getSelectedItemPosition()];if(!a.getSharedPreferences("companion",0).edit().putString("cjk.region",selected).putString("device.name",name.getText().toString().trim()).commit())throw new IllegalStateException();dialog.dismiss();}catch(Exception e){Toast.makeText(a,io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0691,"저장하지 못했어요. 길이와 저장 공간을 확인해 주세요."),Toast.LENGTH_LONG).show();}}));dialog.show();
 }
}
