#ifndef SETTINGS_ICONS_H
#define SETTINGS_ICONS_H
#include "lvgl.h"
#define SETTINGS_ICON_COUNT 6U
enum {SETTINGS_ICON_SPEED,SETTINGS_ICON_WARNING,SETTINGS_ICON_CHECK,SETTINGS_ICON_BACK,SETTINGS_ICON_ADD,SETTINGS_ICON_REMOVE};
const lv_image_dsc_t *Settings_Icon(uint32_t index);
#endif
