"""Reproduce the owned integer-only EVE arc port; never edit pinned LVGL.

Fail on upstream drift instead of applying a textual patch to unknown code.
The generated translation unit preserves the complete upstream algorithm and
MIT notice. Only header paths and the exact power-of-two chord division differ.
"""
from pathlib import Path
import argparse
import hashlib

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'Middlewares/Third_Party/LVGL/src/draw/eve/lv_draw_eve_arc.c'
DEST = ROOT / 'Graphics/Port/src/graphics_eve_arc.c'
SOURCE_SHA = '098945c35a840f15f0d6cff3bc9f4f40188d120d3bb723b9511e248eab4ea9c2'


def expected():
    raw = SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest() != SOURCE_SHA:
        raise ValueError('Pinned LVGL arc changed; review the port and equivalence tests.')
    code = raw.decode().replace('\r\n', '\n')
    changes = {
        '#include "lv_draw_eve_private.h"': '#include "src/draw/eve/lv_draw_eve_private.h"',
        '#include "../lv_draw_arc.h"': '#include "src/draw/lv_draw_arc.h"',
        '#include "lv_eve.h"': '#include "src/draw/eve/lv_eve.h"',
        '    int64_t chord_length = 2 * radius * sin_value / 32768.0;':
        '''    /* Q15 sine and int16 radius keep this product in int32 range:
     * [-2147483648, 2147418112]. Integer /32768 truncates toward zero,
     * exactly like the original double-to-integer conversion. No float
     * precision reduction, table change, or approximate geometry is used. */
    int32_t chord_length = (2 * (int32_t)radius * sin_value) / 32768;''',
    }
    for old, new in changes.items():
        if code.count(old) != 1:
            raise ValueError('Arc patch context is not unique: '+old)
        code = code.replace(old, new)
    licence = (ROOT/'Middlewares/Third_Party/LVGL/LICENCE.txt').read_text(encoding='utf-8')
    return ('/* Generated by tools/eve_arc_port.py from LVGL 9.5.0.\n'
            ' * Upstream source SHA256: '+SOURCE_SHA+'\n'
            ' * Do not hand-edit; the build verifies this exact derivative.\n *\n'
            + ''.join(' * '+line+'\n' for line in licence.splitlines())
            + ' */\n'+code)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    text = expected()
    if args.write:
        DEST.write_text(text, encoding='utf-8', newline='\n')
    elif not DEST.is_file() or DEST.read_text(encoding='utf-8') != text:
        raise ValueError('Owned EVE arc port drifted; regenerate and run equivalence tests.')
    print('Pinned upstream and integer EVE arc port verified.')


if __name__ == '__main__':
    main()
