"""Subset the pinned Google Material Icons Round font to explicit product icons."""
from pathlib import Path
import hashlib,json
from PIL import Image,ImageDraw,ImageFont
P=Path(__file__).resolve().parents[1];A=P/'Graphics/Assets/Icons'
source=A/'source/MaterialIconsRound-Regular.otf'
upstream=json.loads((A/'source/upstream.json').read_text())
assert hashlib.sha256(source.read_bytes()).hexdigest()==upstream['files'][source.name]['sha256']
codepoints=(A/'source/codepoints.txt').read_text()
icons=[('local_gas_station',0xE546),('build',0xE869)]
size=24;font=ImageFont.truetype(str(source),size,layout_engine=ImageFont.Layout.BASIC)
data=[];records=[];glyphs=[' {0},'];maps=[]
for index,(name,cp) in enumerate(icons,1):
 assert f'{name} {cp:04x}' in codepoints
 x0,y0,x1,y1=font.getbbox(chr(cp),anchor='ls');im=Image.new('L',(x1-x0,y1-y0))
 ImageDraw.Draw(im).text((-x0,-y0),chr(cp),font=font,fill=255,anchor='ls')
 # Remove empty margins only; retain Google's raster without stretching.
 crop=im.getbbox();assert crop;im=im.crop(crop);w,h=im.size;start=len(data)
 for y in range(h):
  for x in range(0,w,2):
   hi=(im.getpixel((x,y))*15+127)//255;lo=(im.getpixel((x+1,y))*15+127)//255 if x+1<w else 0
   data.append(hi*16+lo)
 glyphs.append(f' {{.bitmap_index={start},.adv_w={size*16},.box_w={w},.box_h={h},.ofs_x=0,.ofs_y=0}},')
 maps.append(f' {{.range_start=0x{cp:X},.range_length=1,.glyph_id_start={index},.type=LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY}},')
 records.append({'icon':name,'codepoint':cp,'ink_size':[w,h],'ink_offset_top':size-h,'bitmap_index':start,'bitmap_bytes':len(data)-start})
c='''/* Generated by tools/product_icons.py from Google Material Icons Round.
 * Modified: build/local_gas_station subset rasterized to byte-aligned4bpp.
 * Apache-2.0; see Graphics/Assets/Icons/ICON_NOTICES.txt. */
#include "Product_Icons.h"
static const uint8_t bitmap[]={
'''+ '\n'.join(','.join(f'0x{v:02x}' for v in data[i:i+24])+',' for i in range(0,len(data),24))+'''
};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[]={
'''+ '\n'.join(glyphs)+'''
};
static const lv_font_fmt_txt_cmap_t cmaps[]={
'''+ '\n'.join(maps)+'''
};
static const lv_font_fmt_txt_dsc_t dsc={.glyph_bitmap=bitmap,.glyph_dsc=glyphs,
 .cmaps=cmaps,.cmap_num=2,.bpp=4,.bitmap_format=0,.stride=1};
static const lv_font_t font={.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,
 .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=24,.base_line=0,.dsc=&dsc};
/* ROM-only lookup. Unsupported size/name returnsNULL/empty, no substitute icon. */
const lv_font_t *Product_IconFont(uint32_t pixels){return pixels==24U?&font:NULL;}
const char *Product_IconText(ProductIcon id)
{
 switch(id){
 case PRODUCT_ICON_BUILD:return "\\xEE\\xA1\\xA9";
 case PRODUCT_ICON_LOCAL_GAS_STATION:return "\\xEE\\x95\\x86";
 default:return "";
 }
}
'''
from product_aux_assets import transform_icons
target=P/'Graphics/UI/src/product_icon_fonts.c';target.write_text(transform_icons(target.name,c),encoding='utf-8')
record={'family':'Google Material Icons Round','icons':records,'size':size,'line_height':24,'base_line':0,'bitmap_bytes':len(data),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'generated_sha256':hashlib.sha256(target.read_bytes()).hexdigest()}
(A/'manifest.json').write_text(json.dumps(record,indent=2)+'\n')
notice='Google Material Icons Round / build, local_gas_station\nCopyright 2019 Google LLC. All Rights Reserved.\nSource: '+upstream['repository']+'\nCommit: '+upstream['commit']+'\nModified by this project: subset and static4bpp bitmap conversion.\n\n'+(A/'source/LICENSE').read_text()
(A/'ICON_NOTICES.txt').write_text(notice,encoding='utf-8');print(json.dumps(record,indent=2))
