"""Build separate text and number assets for LVGL's static 4bpp EVE path.

TTF/OTF stays on the PC. Device glyphs are uncompressed and byte-aligned.
Text preserves natural advances; numeric digits use centered fixed cells.
No glyph is stretched or artificially emboldened.
"""
import hashlib
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, __version__

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'Graphics/Assets/Fonts'
FAMILIES = {
    'text': ('lato/Lato-Regular.ttf', 'd636e4683231f931eda222d588e944d082bfd3bdba02f928bee461c0f185b251',
             {16: range(32, 127), 20: range(32, 127), 24: range(32, 127), 32: range(32, 127)}, 'Product_TextFonts.h', 'Product_TextFont'),
    'number': ('ddin/D-DIN.otf', '6d67834e2a76646c456c087ce42a6bd6b6b0c85c88dd9918618a8b4c563c2bdf',
               {**{size: tuple(map(ord, ' #+,-.0123456789:/')) + ((34,39) if size==32 else ()) for size in (20, 32, 36, 40, 48, 64)},160:range(48,58)},
               'Product_NumberFonts.h', 'Product_NumberFont'),
}


def build_family(role, spec):
    """Rasterize pinned glyphs and record exact advances and baselines.

    Number slots normalize 0..9 advances only; punctuation and spaces remain
    natural. The narrow '1' is centered without altering its raster. Pixel
    rounding is fixed here; no runtime shaping/allocation is needed.
    """
    filename, expected, sizes, header, api = spec
    source = ASSETS / 'source' / filename
    assert hashlib.sha256(source.read_bytes()).hexdigest() == expected
    chunks = [f'/* Generated by tools/product_fonts.py. Source/license: Graphics/Assets/Fonts/source/{filename}. */',
              f'#include "{header}"', '#if NOODOE_PRODUCT\n#include "Resources.h"\n#include "Product_FontBinding.h"\n#endif']
    records = {}
    unicode_maps = {}
    cmap_maps = {}
    for size, codepoints in sizes.items():
        cps = sorted(set(codepoints))
        face=source
        if role=='text' and size==32:
            face=ASSETS/'source/lato/Lato-Bold.ttf'
            assert hashlib.sha256(face.read_bytes()).hexdigest()=='8a0aace75d33794eece4b28187bfc1df0bbd2888b5d8a56e01788c8d65d16be1'
        font = ImageFont.truetype(str(face), size, layout_engine=ImageFont.Layout.BASIC)
        cell = max(round(font.getlength(c)) for c in '0123456789')
        top = min(font.getbbox(chr(c), anchor='ls')[1] for c in cps)
        bottom = max(font.getbbox(chr(c), anchor='ls')[3] for c in cps)
        line, base = bottom - top + 4, bottom + 2
        bitmap, glyphs, entries = bytearray(), [(0, 0, 0, 0, 0, 0)], []
        for cp in cps:
            char = chr(cp)
            natural = round(font.getlength(char))
            advance = cell if role == 'number' and char.isdigit() else natural
            x0, y0, x1, y1 = font.getbbox(char, anchor='ls')
            w, h = x1 - x0, y1 - y0
            shifted_x = x0 + (advance - natural) // 2
            im = Image.new('L', (max(w, 1), max(h, 1)))
            ImageDraw.Draw(im).text((-x0, -y0), char, font=font, fill=255, anchor='ls')
            offset = len(bitmap)
            for y in range(h):
                for x in range(0, w, 2):
                    hi = (im.getpixel((x, y)) * 15 + 127) // 255
                    lo = (im.getpixel((x+1, y)) * 15 + 127) // 255 if x+1 < w else 0
                    bitmap.append((hi << 4) | lo)
            glyphs.append((offset, advance * 16, w, h, shifted_x, -y1))
            assert line - base - h + y1 >= 0 and line - base + y1 <= line
            entries.append({'codepoint': cp, 'advance': advance, 'natural_advance': natural,
                            'bitmap_index': offset, 'box': [w, h, shifted_x, -y1]})
        name = prefix = f'product_{role}_{size}'
        chunks.append(f'#if !NOODOE_PRODUCT\nstatic const uint8_t {prefix}_bitmap[]={{\n' +
                      '\n'.join(','.join(f'0x{v:02x}' for v in bitmap[i:i+24])+',' for i in range(0, len(bitmap), 24)) + '\n};\n#endif')
        chunks.append(f'static const lv_font_fmt_txt_glyph_dsc_t {prefix}_glyphs[]={{\n' +
                      '\n'.join('{.bitmap_index=%d,.adv_w=%d,.box_w=%d,.box_h=%d,.ofs_x=%d,.ofs_y=%d},' % g for g in glyphs) + '\n};')
        if cps == list(range(cps[0], cps[-1]+1)):
            cmap = '.type=LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY'
        else:
            offsets = tuple(c-cps[0] for c in cps)
            if offsets not in unicode_maps:
                unicode_maps[offsets] = prefix+'_unicode'
                chunks.append(f'static const uint16_t {prefix}_unicode[]={{' + ','.join(map(str,offsets)) + '};')
            cmap = f'.unicode_list={unicode_maps[offsets]},.list_length={len(cps)},.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY'
        definition = '{.range_start=%d,.range_length=%d,.glyph_id_start=1,' % (cps[0],cps[-1]-cps[0]+1) + cmap + '}'
        if definition not in cmap_maps:
            cmap_maps[definition] = prefix+'_map'
            chunks.append('static const lv_font_fmt_txt_cmap_t '+cmap_maps[definition]+'[]={'+definition+'};')
        chunks.append(f'static lv_font_fmt_txt_dsc_t {prefix}_dsc={{\n#if !NOODOE_PRODUCT\n.glyph_bitmap={prefix}_bitmap,\n#endif\n.glyph_dsc={prefix}_glyphs,' +
                      f'.cmaps={cmap_maps[definition]},.cmap_num=1,.bpp=4,.bitmap_format=0,.stride=1}};')
        chunks.append(f'const lv_font_t {name}={{.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,' +
                      f'.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height={line},.base_line={base},.dsc=&{prefix}_dsc}};')
        records[name] = {'source_face':str(face.relative_to(ASSETS/'source')),'source_sha256':hashlib.sha256(face.read_bytes()).hexdigest(),'role': role, 'size': size, 'line_height': line, 'base_line': base,
                         'digit_cell_width': cell, 'bitmap_bytes': len(bitmap), 'glyphs': entries}
    chunks.append('/* Return a prebuilt font; unsupported sizes return NULL, never a scaled substitute. */\n' +
                  f'const lv_font_t *{api}(uint32_t pixels)\n{{\n    switch(pixels){{\n' +
                  '\n'.join(f'    case {s}U:return &product_{role}_{s};' for s in sizes) +
                  '\n    default:return NULL;\n    }\n}')
    auxiliary=('    extern uint32_t Product_AuxAssetsBind(void);\n    if(!Product_AuxAssetsBind())return 0;\n' if role=='text' else '')
    chunks.append(f'uint32_t Product_{role.title()}FontsBind(void)\n{{\n#if NOODOE_PRODUCT\n'+auxiliary+'    static const ProductFontBinding bindings[]={' + ','.join('{RESOURCE_PRODUCT_%s_%d,&product_%s_%d_dsc}' % (role.upper(),size,role,size) for size in sizes) + '};\n    return Product_FontsBindTable(bindings,sizeof(bindings)/sizeof(bindings[0]));' + '\n#endif\n    return 1;\n}')
    out = ROOT / f'Graphics/UI/src/product_{role}_fonts.c'
    out.write_text('\n\n'.join(chunks)+'\n', encoding='utf-8')
    return {'source': filename, 'source_sha256': expected, 'generated': out.name,
            'generated_sha256': hashlib.sha256(out.read_bytes()).hexdigest(), 'fonts': records}


def generate():
    """Publish both independent font families and their verification manifest."""
    result = {'pillow': __version__, 'bpp': 4, 'compressed': False, 'kerning': False,
              'families': {role: build_family(role, spec) for role, spec in FAMILIES.items()}}
    (ASSETS / 'manifest.json').write_text(json.dumps(result, indent=2)+'\n', encoding='utf-8')
    print(json.dumps({role: {name: {k: v for k, v in font.items() if k != 'glyphs'}
                             for name, font in family['fonts'].items()}
                      for role, family in result['families'].items()}, indent=2))


if __name__ == '__main__':
    generate()
