"""Keep auxiliary glyph/mask bytes in RSC without editing pinned LVGL.

Only Product externalizes data. Generated metrics, mapping and raster bytes are
unchanged; other profiles retain their existing in-image fonts. Icon generators
call transform_icons before publishing so regeneration preserves this contract.
"""
from pathlib import Path
import hashlib,json,re
P=Path(__file__).resolve().parents[1]
ICONS={
 'product_mode_icon_data.c':('mode','Product_ModeIconsBind',8),
 'product_trip_icon_data.c':('trip','Product_TripIconsBind',4),
 'product_music_icon_data.c':('music','Product_MusicIconsBind',6),
 'settings_icon_data.c':('settings','Product_SettingsIconsBind',6),
}
def transform_icons(name,text):
    """Wrap existing byte literals; do not regenerate or rescale any pixel."""
    if 'NOODOE_AUX_EXTERNAL_DATA' in text:return text
    if name not in ICONS and name!='product_icon_fonts.c':raise ValueError(name)
    header='\n/* NOODOE_AUX_EXTERNAL_DATA: fixed descriptors bind once before UI startup. */\n#include "Product_AuxAssets.h"\n#if NOODOE_PRODUCT\n#include "Resources.h"\n#endif\n'
    at=text.index('\n',text.index('#include '))+1;text=text[:at]+header+text[at:]
    if name in ICONS:
        role,api,count=ICONS[name]
        m=re.search(r'static const uint8_t masks\[.*?\n\};',text,re.S)
        if not m:raise ValueError('Missing masks '+name)
        text=text[:m.start()]+'#if !NOODOE_PRODUCT\n'+m.group(0)+'\n#define AUX_MASK(n) masks[n]\n#else\n#define AUX_MASK(n) NULL\n#endif'+text[m.end():]
        text=text.replace('static const lv_image_dsc_t icons','static lv_image_dsc_t icons')
        text=re.sub(r'\.data=masks\[(\d+)\]',r'.data=AUX_MASK(\1)',text)
        text+=f'''\n/* UI owner only: validated immutable SDRAM bytes outlive all cached images. */
uint32_t {api}(void)
{{
#if NOODOE_PRODUCT
    ResourceView v;
    if(!Resources_Get(RESOURCE_ICON_{role.upper()},&v)||v.bytes!={count*288}U)return 0;
    for(uint32_t i=0;i<{count}U;++i)icons[i].data=v.data+i*288U;
#endif
    return 1;
}}
'''
    else:
        m=re.search(r'static const uint8_t bitmap\[\].*?\n\};',text,re.S)
        if not m:raise ValueError('Missing footer bitmap')
        text=text[:m.start()]+'#if !NOODOE_PRODUCT\n'+m.group(0)+'\n#define AUX_BITMAP bitmap\n#else\n#define AUX_BITMAP NULL\n#endif'+text[m.end():]
        text=text.replace('static const lv_font_fmt_txt_dsc_t dsc','static lv_font_fmt_txt_dsc_t dsc').replace('.glyph_bitmap=bitmap','.glyph_bitmap=AUX_BITMAP')
        text+='''\n/* Keep all glyph metrics/cmaps internal; no runtime file callbacks. */
uint32_t Product_FooterIconsBind(void)
{
#if NOODOE_PRODUCT
    ResourceView v;
    if(!Resources_Get(RESOURCE_ICON_FOOTER,&v)||v.bytes!=404U)return 0;
    dsc.glyph_bitmap=v.data;
#endif
    return 1;
}
'''
    return text

def montserrat():
    """Produce a project-owned copy with an external bitmap, retaining metrics.

    The original vendored source remains byte-identical and is excluded only
    from Product. This file replaces that one symbol in Product, not LVGL APIs.
    """
    source=P/'Middlewares/Third_Party/LVGL/src/font/lv_font_montserrat_14.c'
    original=source.read_text(encoding='utf-8');text=original
    text=re.sub(r'#ifdef LV_LVGL_H_INCLUDE_SIMPLE.*?#endif', '#include "lvgl.h"\n#include "Product_AuxAssets.h"\n#include "Resources.h"',text,count=1,flags=re.S)
    text=text.replace('#if LV_FONT_MONTSERRAT_14','#if NOODOE_PRODUCT && LV_FONT_MONTSERRAT_14',1)
    m=re.search(r'static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap\[\]\s*=\s*\{.*?\n\};',text,re.S)
    if not m:raise ValueError('Pinned Montserrat layout changed')
    text=text[:m.start()]+'/* Bitmap is provided by the immutable verified resource arena. */'+text[m.end():]
    text=text.replace('static const lv_font_fmt_txt_dsc_t font_dsc','static lv_font_fmt_txt_dsc_t font_dsc').replace('.glyph_bitmap = glyph_bitmap','.glyph_bitmap = NULL')
    end=text.rfind('#endif /*#if LV_FONT_MONTSERRAT_14*/')
    text=text[:end]+'''/* Bind before lv_init/default theme creation, never while rendering. */
uint32_t Product_MontserratBind(void)
{
    ResourceView v;
    if(!Resources_Get(RESOURCE_FONT_MONTSERRAT_14,&v)||v.bytes!=8832U)return 0;
    font_dsc.glyph_bitmap=v.data;
    return 1;
}
'''+text[end:]
    notice='/* Project-owned data-placement derivative; generated by tools/product_aux_assets.py.\n * Upstream LVGL MIT license remains in Middlewares/Third_Party/LVGL/LICENCE.txt.\n * Metrics/kerning/cmaps unchanged. Upstream source SHA256: '+hashlib.sha256(source.read_bytes()).hexdigest()+' */\n'
    return notice+text

def generate():
    for name in [*ICONS,'product_icon_fonts.c']:
        path=P/'Graphics/UI/src'/name;path.write_text(transform_icons(name,path.read_text(encoding='utf-8')),encoding='utf-8')
    (P/'Graphics/UI/src/product_montserrat_font.c').write_text(montserrat(),encoding='utf-8')

if __name__=='__main__':generate()
