"""One immutable24px Material Rounded call mask, shared by shell/carousel/hints."""
from pathlib import Path
import hashlib,json
from PIL import Image,ImageDraw,ImageFont
P=Path(__file__).resolve().parents[1];A=P/'Graphics/Assets/Icons/source'
source=A/'MaterialIconsRound-Regular.otf'
assert hashlib.sha256(source.read_bytes()).hexdigest()==json.loads((A/'upstream.json').read_text())['files'][source.name]['sha256']
points=dict(line.split() for line in (A/'codepoints.txt').read_text().splitlines())
font=ImageFont.truetype(str(source),24,layout_engine=ImageFont.Layout.BASIC)
cp=int(points['call'],16);im=Image.new('L',(48,48));ImageDraw.Draw(im).text((8,32),chr(cp),font=font,anchor='ls',fill=255)
ink=im.crop(im.getbbox());assert ink.width<=24 and ink.height<=24
im=Image.new('L',(24,24));im.paste(ink,((24-ink.width)//2,(24-ink.height)//2))
values=[(x*15+127)//255 for x in im.tobytes()];data=[a*16+b for a,b in zip(values[::2],values[1::2])]
c='/* Generated by product_call_icon.py; Google Material Icons Round, Apache-2.0.\n * See Graphics/Assets/Icons/ICON_NOTICES.txt. Native24px alpha4,288bytes. */\n#include "Product_CallIcon.h"\nstatic const uint8_t pixels[]={\n'
c+='\n'.join(','.join(str(x) for x in data[i:i+24])+',' for i in range(0,len(data),24))
c+='\n};\nstatic const lv_image_dsc_t icon={.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_A4,.w=24,.h=24,.stride=12},.data_size=288,.data=pixels};\nconst lv_image_dsc_t *Product_CallIcon(void){return &icon;}\n'
(P/'Graphics/UI/src/product_call_icon.c').write_text(c,encoding='utf-8')
