"""Package exact generated 4bpp glyphs and both TI scripts; never rasterize here.

One 1MiB file contains two independent 512KiB slots. A slot is published only
when its final commit word is present. SHA binds entry metadata and payload;
per-entry CRC catches local damage. This is integrity, not authentication.
"""
from pathlib import Path
import hashlib,json,re,struct,zlib,sys
ROOT=Path(__file__).resolve().parents[1]
SLOT=512*1024
HEADER=4096
MAGIC=0x31534352
COMMIT=0x434d5431
def arrays(path,pattern):
    text=path.read_text(encoding='utf-8')
    return [(name,bytes(int(v,16) for v in re.findall(r'0x([0-9a-fA-F]{2})\b',body)))
            for name,body in re.findall(pattern,text,re.S)]
def generate(check=False):
    def publish(path,data):
        if check:
            if not path.exists() or path.read_bytes()!=data:raise ValueError("Stale resource package: "+str(path))
        else:path.write_bytes(data)
    entries=[];additional=[]
    for role in ('text','number'):
        for name,data in arrays(ROOT/f'Graphics/UI/src/product_{role}_fonts.c',r'static const uint8_t (product_\w+_bitmap)\[\]\s*=\s*\{(.*?)\};'):
            (additional if name=='product_number_160_bitmap' else entries).append((name.removesuffix('_bitmap'),data))
    for rev in ('b','c'):
        path=ROOT/f'Middlewares/Noodoe/Bluetooth/patches/cc256x{rev}.inc'
        text=path.read_text()
        body=re.search(r'cc256x_init_script\[\]\s*=\s*\{(.*?)\};',text,re.S).group(1)
        body=re.sub(r'/\*.*?\*/|//[^\n]*','',body,flags=re.S)
        entries.append((f'bt_cc256x{rev}',bytes(int(v,16) for v in re.findall(r'0x([0-9a-fA-F]{2})\b',body))))
    assert len(entries)==12
    # Keep IDs1..12 stable for existing Lato/D-DIN/TI consumers. Auxiliary
    # rasters move byte-for-byte; their descriptors/metrics stay internal.
    auxiliary=[('font_montserrat_14','Middlewares/Third_Party/LVGL/src/font/lv_font_montserrat_14.c','glyph_bitmap'),
               ('icon_mode','Graphics/UI/src/product_mode_icon_data.c','masks'),
               ('icon_trip','Graphics/UI/src/product_trip_icon_data.c','masks'),
               ('icon_music','Graphics/UI/src/product_music_icon_data.c','masks'),
               ('icon_settings','Graphics/UI/src/settings_icon_data.c','masks'),
               ('icon_footer','Graphics/UI/src/product_icon_fonts.c','bitmap')]
    for name,path,symbol in auxiliary:
        text=(ROOT/path).read_text(encoding='utf-8')
        body=re.search(r'const uint8_t '+symbol+r'\[.*?\n\};',text,re.S).group(0)
        body=re.sub(r'/\*.*?\*/|//[^\n]*','',body,flags=re.S)
        data=bytes(int(v,16) for v in re.findall(r'0x([0-9a-fA-F]{1,2})\b',body))
        entries.append((name,data))
    assert [len(data) for _,data in entries[12:]]==[8832,2304,1152,1728,1728,404]
    entries.append(("icon_status",(ROOT/"Graphics/Assets/Icons/status-masks.bin").read_bytes()))
    # Append only. Existing package IDs 1..19 remain stable across upgrades.
    assert sum(len(d) for _,d in entries)==102183
    entries.extend(additional)
    payload=bytearray();table=bytearray();records=[]
    for i,(name,data) in enumerate(entries,1):
        payload.extend(b'\0'*((-len(payload))%4))
        off=len(payload);payload.extend(data)
        crc=zlib.crc32(data);table.extend(struct.pack('<4I',i,off,len(data),crc))
        records.append(dict(id=i,name=name,offset=off,bytes=len(data),crc32=crc,sha256=hashlib.sha256(data).hexdigest()))
    assert HEADER+len(payload)<=SLOT and len(entries)*16<=4088-48
    digest=hashlib.sha256(table+payload).digest()
    header=bytearray(b'\xff'*HEADER)
    struct.pack_into('<4I',header,0,MAGIC,1,len(payload),len(entries))
    header[16:48]=digest;header[48:48+len(table)]=table
    struct.pack_into('<2I',header,4088,zlib.crc32(header[:4088]),COMMIT)
    slot=bytes(header+payload)+b'\xff'*(SLOT-HEADER-len(payload))
    out=ROOT/'Resources';out.mkdir(exist_ok=True)
    publish(out/'NOODOE.RSC',slot+b'\xff'*SLOT)
    publish(out/'slot.bin',slot)
    manifest=dict(format=1,required_sha256=digest.hex(),container_bytes=2*SLOT,slot_bytes=SLOT,entries=records)
    publish(out/'manifest.json',(json.dumps(manifest,indent=2)+'\n').encode())
    inc=ROOT/'Middlewares/Noodoe/Resources/inc';inc.mkdir(parents=True,exist_ok=True)
    lines=['/* Generated by tools/resource_pack.py; do not hand edit. */','#ifndef RESOURCES_EXPECTED_H','#define RESOURCES_EXPECTED_H',
           f'#define RESOURCES_COUNT {len(entries)}U',f'#define RESOURCES_PAYLOAD_BYTES {len(payload)}U',
           '#define RESOURCES_EXPECTED_SHA {'+','.join(f'0x{x:02x}' for x in digest)+'}']
    for r in records:lines.append(f'#define RESOURCE_{r["name"].upper()} {r["id"]}U')
    lines+=['#endif']
    publish(inc/'Resources_Expected.h',('\n'.join(lines)+'\n').encode())
    print(json.dumps({k:v for k,v in manifest.items() if k!='entries'}))
if __name__=='__main__':generate('--check' in sys.argv)
