"""Build isolated UninstallBootstrap; append-only S4 journal, S5-S7 code + stock. No Cube regeneration or hardware access."""
from pathlib import Path
from bootstrap_pack import pack
import argparse,concurrent.futures,hashlib,json,subprocess
P=Path(__file__).resolve().parents[1]
TC=Path('C:/ST/STM32CubeIDE_1.18.1/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.13.3.rel1.win32_1.0.0.202411081344/tools/bin')
def build(out,stock):
 out=out.resolve();out.mkdir(parents=True,exist_ok=True)
 pack(stock,out)
 includes=[P/x for x in ['UninstallBootstrap/include','App_Logic/Bootstrap/inc','Middlewares/Third_Party/miniz','RecoveryGate/include','Drivers/BSP/inc','Drivers/CMSIS/Include','Drivers/CMSIS/Device/ST/STM32F4xx/Include','Middlewares/Noodoe/Update/inc','Middlewares/Noodoe/Storage/inc','Middlewares/Noodoe/Resources/inc']]
 sources=[P/'RecoveryGate/src'/x for x in ['gate_board.c','gate_display.c','gate_store.c','gate_format.c','gate_policy.c','event_log.c']]
 sources += list((P/'UninstallBootstrap/src').glob('*.c'))+[P/'UninstallBootstrap/startup/uninstall_reset.s',P/'Drivers/BSP/src/bsp_watchdog.c',P/'App_Logic/Bootstrap/src/bootstrap_image.c',P/'Middlewares/Third_Party/miniz/miniz_tinfl.c',out/'stock_asset.s']
 sources += [P/'Drivers/BSP/src/noodoe_crc32.c']
 sources += [P/'Middlewares/Noodoe/Update/src'/f for f in ['Update_SHA256.c','Update_Metadata.c','Recovery_Core.c']]
 sources += [P/'Middlewares/Noodoe/Storage/src/recovery_store.c',P/'Middlewares/Noodoe/Resources/src/Resources_Format.c']
 flags=['-mcpu=cortex-m4','-mthumb','-mfpu=fpv4-sp-d16','-mfloat-abi=hard','-Oz','-g3','-ffunction-sections','-fdata-sections','-fstack-usage','-Wall','-Wextra','-Werror','-DNDEBUG','-DSTM32F429xx','-DNOODOE_PRODUCT=0','-DNOODOE_RECOVERY_GATE=1','-DNOODOE_UNINSTALL=1','-DNOODOE_BOOTSTRAP=0','-DMINIZ_NO_ARCHIVE_APIS','-DMINIZ_NO_DEFLATE_APIS','-DMINIZ_NO_STDIO','-DMINIZ_NO_TIME','-DMINIZ_NO_MALLOC','-DMINIZ_NO_ZLIB_APIS','-Wno-misleading-indentation','--specs=nano.specs']+['-I'+str(i) for i in includes]
 def compile(src):
  obj=out/(src.stem+'.o');r=subprocess.run([str(TC/'arm-none-eabi-gcc.exe'),*flags,'-c',str(src),'-o',str(obj)],capture_output=True,text=True)
  (out/(src.stem+'.log')).write_text(r.stdout+r.stderr)
  if r.returncode:raise RuntimeError(str(src)+'\n'+r.stderr)
  return obj
 with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:objects=list(pool.map(compile,sources))
 elf=out/'uninstall.elf';binary=out/'uninstall.bin'
 cmd=[str(TC/'arm-none-eabi-gcc.exe'),*flags,'-nostartfiles','--specs=nosys.specs',*map(str,objects),'-Wl,-T,'+str(P/'UninstallBootstrap/linker/uninstall.ld'),'-Wl,--gc-sections','-Wl,-Map,'+str(out/'uninstall.map'),'-Wl,--print-memory-usage','-o',str(elf)]
 r=subprocess.run(cmd,capture_output=True,text=True);(out/'link.log').write_text(r.stdout+r.stderr)
 if r.returncode:raise RuntimeError(r.stdout+r.stderr)
 subprocess.run([str(TC/'arm-none-eabi-objcopy.exe'),'-O','binary','--gap-fill=0xFF',str(elf),str(binary)],check=True)
 data=binary.read_bytes();assert len(data)<=0x70000
 assert data[0x1000:0x10000]==bytes([255])*0xf000
 data=data.ljust(0x70000,b'\xff');binary.write_bytes(data)
 result={'base':hex(0x08010000),'bytes':len(data),'journal_bytes':0xf000,'code_capacity':0x60000,'sha256':hashlib.sha256(data).hexdigest(),'sources':len(sources),'hardware_tested':False,'depends_on':['HSI','LSI/IWDG','internal SRAM','SPI5 NOR'],'not_used':['RTOS','SDRAM','LVGL','Bluetooth','HSE']}
 (out/'manifest.json').write_text(json.dumps(result,indent=2)+'\n')
 header=P/'Middlewares/Noodoe/Update/inc/Uninstall_Expected.h'
 header.write_text('/* Generated by uninstall_build.py from the exact verified standalone image. */\n#ifndef UNINSTALL_EXPECTED_H\n#define UNINSTALL_EXPECTED_H\n#define UNINSTALL_TRANSPORT_VERSION 7U\n#define UNINSTALL_IMAGE_SHA {'+','.join('0x'+result['sha256'][i:i+2] for i in range(0,64,2))+'}\n#endif\n')
 print(r.stdout);print(json.dumps(result,indent=2));return result
if __name__=='__main__':
 a=argparse.ArgumentParser(description=__doc__);a.add_argument('--output',type=Path,required=True);a.add_argument('--stock',type=Path,required=True);args=a.parse_args();build(args.output,args.stock)
