package io.opennoodoe.app.maintenance;
import android.app.*;
import android.os.*;
import android.widget.*;
import io.opennoodoe.app.companion.DeviceSettingsSession;
import java.util.*;
/** Typed editor over a RAM snapshot. Service worker alone performs requests;
 * closing a dialog cannot interrupt storage or duplicate an action. */
final class DeviceSettingsDialog {
 static void show(Activity a,MaintenanceService service){
  DeviceSettingsSession s=service==null?null:service.deviceSettings();
  if(s==null){new AlertDialog.Builder(a).setMessage(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0000,"주행 연결 후 기기에서 읽은 설정을 표시해요.")).setPositiveButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0001,"확인"),null).show();return;}
  s.refresh();LinearLayout root=new LinearLayout(a);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,16,24,16);
  TextView state=new TextView(a);root.addView(state);
  Button name=new Button(a);name.setText(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0002,"라이더 이름"));name.setEnabled(s.available);root.addView(name);name.setOnClickListener(v->{EditText input=new EditText(a);input.setSingleLine(true);input.setText(s.text(0x201));new AlertDialog.Builder(a).setTitle(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0002,"라이더 이름")).setMessage(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0003,"UTF-8 최대 48바이트. 저장 후 기기에서 표시해요.")).setView(input).setNegativeButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0004,"취소"),null).setPositiveButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0005,"적용"),(d,w)->{if(!s.name(input.getText().toString()))Toast.makeText(a,io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0006,"이름 길이와 연결 상태를 확인해 주세요."),Toast.LENGTH_LONG).show();}).show();});
  Button odo=new Button(a);odo.setText(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0007,"ODO 보존값 확인"));odo.setEnabled(s.available);root.addView(odo);odo.setOnClickListener(v->odo(a,s));
  LinearLayout list=new LinearLayout(a);list.setOrientation(LinearLayout.VERTICAL);ScrollView scroll=new ScrollView(a);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,(int)(370*a.getResources().getDisplayMetrics().density)));
  AlertDialog dialog=new AlertDialog.Builder(a).setTitle(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0008,"기기의 모든 설정")).setView(root).setNegativeButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0009,"닫기"),null).setNeutralButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0010,"새로고침"),null).create();
  Handler h=new Handler(Looper.getMainLooper());final String[] previous={""};
  Runnable refresh=new Runnable(){public void run(){if(!dialog.isShowing())return;
   if(service.deviceSettings()!=s){dialog.dismiss();Toast.makeText(a,s.status,Toast.LENGTH_LONG).show();return;}
   state.setText(s.status+"\n"+(s.ready?io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0011,"정차 확인됨"):io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0012,"변경하려면 시동 ON · 3 km/h 이하를 5초 유지하세요.")));
   List<long[]> rows=s.rows();String key=Arrays.deepToString(rows.toArray());if(!key.equals(previous[0])){previous[0]=key;list.removeAllViews();
    for(long[] r:rows){Button b=new Button(a);b.setText(label((int)r[0])+"  ·  "+value(r));list.addView(b);b.setOnClickListener(v->edit(a,s,r));}}
   h.postDelayed(this,300);
  }};
  dialog.setOnDismissListener(d->h.removeCallbacks(refresh));dialog.show();dialog.getButton(-3).setOnClickListener(v->{previous[0]="";s.refresh();});h.post(refresh);
 }
 static String label(int id){switch(id){
  case 0x1070:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.notification_preview,"알림 자동 표시");case 0x1071:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.notification_preview_seconds,"알림 표시 시간 (초)");
  case 0x1001:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0013,"밝기 모드");case 0x1002:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0014,"누도 밝기 (%)");case 0x1003:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0015,"누도 자동 밝기 보정");
  case 0x1004:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0016,"배경 표시");case 0x1005:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0017,"사진 슬롯");case 0x1006:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0018,"배경 중앙 밝기 (%)");case 0x1007:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0019,"키 OFF 사진");case 0x1008:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0020,"계기판 UART 밝기 단계 보정");
  case 0x1010:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0021,"UTC 시간대 (분)");case 0x1011:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0022,"거리 단위");case 0x1012:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0023,"속도 링 최대값 (km/h)");case 0x1013:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0024,"차종 · 읽기 전용");case 0x1014:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0025,"정차 임계 속도 (km/h)");case 0x1015:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0026,"기기 UI 언어 · 읽기 전용");
  case 0x1020:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0027,"화면 유지 시간 (분)");case 0x1021:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0028,"Bluetooth 유지 시간 (분)");case 0x1022:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0029,"화면 유지 단계");case 0x1023:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0030,"Bluetooth 유지 단계");case 0x1024:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0031,"완전 절전 단계");
  case 0x1030:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0032,"오일 교체 거리 (km)");case 0x1031:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0033,"오일 교체 시동 시간 (h)");case 0x1032:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0034,"오일 교체 일수");
  case 0x1040:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0035,"벨트 교체 거리 (km)");case 0x1041:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0036,"벨트 교체 시동 시간 (h)");case 0x1042:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0037,"벨트 교체 일수");
  case 0x1050:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0038,"정비 거리 (km)");case 0x1051:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0039,"정비 시동 시간 (h)");case 0x1052:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0040,"정비 일수");
  case 0x1060:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0041,"기기 테마");case 0x1061:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0042,"자동 테마 기준");case 0x1062:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0043,"라이트 모드 시작");case 0x1063:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0044,"다크 모드 시작");case 0x1064:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0045,"다크 전환 조도 (lux)");case 0x1065:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0046,"라이트 전환 조도 (lux)");
  case 0x3001:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0047,"날짜");case 0x3002:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0048,"시간");case 0x3003:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0049,"오일 교체 완료");case 0x3004:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0050,"벨트 교체 완료");case 0x3005:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0051,"정비 완료");case 0x3006:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0052,"화면 설정 초기화");
  case 0x3007:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0053,"Bluetooth 페어링 허용");case 0x3008:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0054,"페어링 닫기");case 0x3009:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0055,"Bluetooth 연결 종료");case 0x300a:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0056,"Bluetooth 재페어링");case 0x300b:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0057,"Bluetooth 재시작");case 0x300c:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0058,"조도센서 재시도");
  case 0x4001:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0059,"연결 휴대전화");case 0x4002:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0060,"Bluetooth 상태");case 0x4003:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0061,"펌웨어 버전");case 0x4004:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0062,"자동 밝기 상태");case 0x4005:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0063,"최종 절전 대기");
  case 0x8000:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0060,"Bluetooth 상태");case 0x8001:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0064,"BT 컨트롤러·패치");case 0x8002:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0065,"SPP 전송량");case 0x8003:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0066,"SPP 큐·오류");case 0x8004:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0067,"주변 조도");case 0x8005:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0068,"조도 RAW·경과");case 0x8006:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0069,"조도 칩·설정");case 0x8007:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0070,"조도 I2C 상태");case 0x8008:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0071,"계기판 UART");case 0x8009:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0072,"UART 프레임");case 0x800a:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0073,"조도 원본·보정·송신");case 0x800b:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0074,"UART 속도·연료 RAW");case 0x800c:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0075,"휴대전화 GPS");case 0x800d:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0076,"시동 입력");case 0x800e:return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0077,"PH9 입력 모드");
  default:return String.format(Locale.ROOT,"0x%04X",id);
 }}
 private static String[] options(long field){switch((int)field){
  case 0x1001:return new String[]{io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0078,"수동"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0079,"자동")};case 0x1011:return new String[]{"km","mi"};
  case 0x1070:case 0x1004:case 0x1022:case 0x1023:case 0x1024:return new String[]{io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0080,"끄기"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0081,"켜기")};
  case 0x1005:return new String[]{io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0082,"사진 0"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0083,"사진 1"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0084,"사진 2")};case 0x1007:return new String[]{io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0085,"주행 배경과 동일"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0082,"사진 0"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0083,"사진 1"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0084,"사진 2")};
  case 0x1060:return new String[]{io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0086,"다크"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0087,"라이트"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0079,"자동")};case 0x1061:return new String[]{io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0088,"조도 센서"),io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0089,"시간표")};default:return null;
 }}
 private static String value(long[] r){if(r[5]==2||r[5]==3)return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0090,"조회");if(r[5]==4||r[5]==8)return io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0091,"실행");String[] o=options(r[0]);return o!=null&&r[1]>=0&&r[1]<o.length?o[(int)r[1]]:Long.toString(r[1]);}
 private static void submit(Activity a,DeviceSettingsSession s,long[] r,int v){if(!s.edit(r[0],v,r[1]))Toast.makeText(a,io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0092,"요청 대기열이 가득 찼어요."),Toast.LENGTH_LONG).show();}
 private static void edit(Activity a,DeviceSettingsSession s,long[] r){
  String title=label((int)r[0]);int kind=(int)r[5];
  if(kind==2||kind==3){TextView text=new TextView(a);text.setPadding(32,24,32,24);s.read(r[0]);AlertDialog d=new AlertDialog.Builder(a).setTitle(title).setView(text).setPositiveButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0009,"닫기"),null).create();Handler h=new Handler(Looper.getMainLooper());Runnable tick=new Runnable(){public void run(){if(!d.isShowing())return;text.setText(s.text(r[0])+"\n"+s.status);h.postDelayed(this,300);}};d.setOnDismissListener(x->h.removeCallbacks(tick));d.show();h.post(tick);return;}
  if(kind==4||kind==8){new AlertDialog.Builder(a).setTitle(title).setMessage(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0093,"이 작업을 실행할까요? Bluetooth 작업은 현재 연결을 종료할 수 있어요. 다시 연결한 뒤 실제 상태를 확인하세요.")).setNegativeButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0004,"취소"),null).setPositiveButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0091,"실행"),(d,w)->submit(a,s,r,1)).show();return;}
  if(kind==6){int date=(int)r[1];new DatePickerDialog(a,(v,y,m,d)->submit(a,s,r,y*10000+(m+1)*100+d),date/10000,date/100%100-1,date%100).show();return;}
  if(kind==7||r[0]==0x1062||r[0]==0x1063){boolean clock=kind==7;int value=(int)r[1];new TimePickerDialog(a,(v,h,m)->submit(a,s,r,clock?h*100+m:h*60+m),clock?value/100:value/60,clock?value%100:value%60,true).show();return;}
  String[] choices=options(r[0]);if(choices!=null){new AlertDialog.Builder(a).setTitle(title).setSingleChoiceItems(choices,(int)r[1],(d,w)->{submit(a,s,r,w);d.dismiss();}).setNegativeButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0004,"취소"),null).show();return;}
  EditText input=new EditText(a);input.setSingleLine(true);input.setInputType(4098);input.setText(Long.toString(r[1]));
  AlertDialog d=new AlertDialog.Builder(a).setTitle(title).setMessage(r[2]+" ~ "+r[3]+(r[0]==0x1008?io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0094,"\n양수는 UART 단계값을 높입니다. 누도 화면 밝기는 바꾸지 않아요."):"")).setView(input).setNegativeButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0004,"취소"),null).setPositiveButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0005,"적용"),null).create();d.show();d.getButton(-1).setOnClickListener(v->{try{int n=Integer.parseInt(input.getText().toString());if(n<r[2]||n>r[3])throw new NumberFormatException();submit(a,s,r,n);d.dismiss();}catch(NumberFormatException e){input.setError(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0095,"범위 안의 정수를 입력해 주세요."));}});
 }
 private static void odo(Activity a,DeviceSettingsSession s){long[] o=s.odometer();if(o.length!=9)return;
  String info=io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0096,"보존 표시: ")+(o[0]!=0?o[2]+" km":io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0097,"알 수 없음"))+io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0098,"\n계기판 수신: ")+o[1]+" km\n"+(o[3]!=0?io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0099,"보정값을 사용 중이에요.\n"):"")+io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0100,"저장 상태: ")+o[8];
  AlertDialog.Builder b=new AlertDialog.Builder(a).setTitle(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0101,"ODO 보존값")).setMessage(info);
  if(o[4]!=0&&o[6]!=0){b.setPositiveButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0102,"보존값 유지"),(d,w)->s.decide(o[7],1)).setNeutralButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0103,"계기판 값 사용"),(d,w)->new AlertDialog.Builder(a).setMessage(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0104,"새 계기판 값을 기준으로 사용할까요?")).setPositiveButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0105,"사용"),(x,y)->s.decide(o[7],2)).setNegativeButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0004,"취소"),null).show());}
  b.setNegativeButton(io.opennoodoe.app.UiText.text(io.opennoodoe.app.R.string.companion_0106,"나중에"),null).show();
 }
}
